name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job runs on every push and PR to build and test the code
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run tests
        run: ./gradlew build
      - name: Upload Test Reports
        if: always() # Always run this step, even if the build fails
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: test-reports
          path: '**/build/reports/tests/test'

  # This job publishes either a SNAPSHOT version on every push to main
  publish:
    runs-on: ubuntu-latest
    needs: build_and_test # This job depends on the build_and_test job
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write # <--- ADDED THIS LINE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract Version and Type
        id: extract_version_info
        run: |
          VERSION=$(grep 'version =' library/build.gradle.kts | grep -o "'.*'" | sed "s/'//g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" == *"-SNAPSHOT"* ]]; then
            echo "is_snapshot=true" >> $GITHUB_OUTPUT
          else
            echo "is_snapshot=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Create GitHub Release
        if: steps.extract_version_info.outputs.is_snapshot == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.extract_version_info.outputs.version }}
          release_name: Release v${{ steps.extract_version_info.outputs.version }}
          body: | # Placeholder for release notes, you'd typically update this manually or from a changelog
            ## Release Notes v${{ steps.extract_version_info.outputs.version }}

            This is an automated release.
            Please see the commit history for changes.
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
